import { createContext, useContext, useState } from 'react';

export const translations = {
  fr: {
    // Nav
    nav_dashboard: 'Tableau de Bord',
    nav_clients: 'Clients',
    nav_invoices: 'Factures',
    nav_stock: 'Stock',
    nav_messaging: 'Messagerie',
    nav_accounting: 'Comptabilité',
    nav_sales: 'Ventes',
    nav_marketing: 'Marketing',
    nav_finance: 'Finance Perso',
    nav_business_plan: 'Business Plan',
    nav_assistant: 'Assistant IA',
    nav_settings: 'Paramètres',
    // Dashboard
    daily_objective: 'Objectif Ventes Quotidien',
    total_revenue: 'Chiffre d\'Affaires',
    net_profit: 'Bénéfice Net',
    expenses: 'Dépenses',
    clients: 'Clients',
    products: 'Produits',
    sales: 'Ventes',
    invoices: 'Factures',
    pending: 'En attente',
    paid: 'Payé',
    overdue: 'En retard',
    stock_alerts: 'Alertes Stock',
    low_stock: 'Stock bas',
    quick_actions: 'Actions Rapides',
    new_sale: 'Nouvelle Vente',
    new_invoice: 'Nouvelle Facture',
    new_client: 'Nouveau Client',
    add_stock: 'Ajouter Stock',
    weekly_revenue: 'Revenus Hebdomadaires',
    margin: 'Marge',
    // General
    save: 'Sauvegarder',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    search: 'Rechercher',
    filter: 'Filtrer',
    export: 'Exporter',
    generate: 'Générer',
    loading: 'Chargement…',
    confirm: 'Confirmer',
    close: 'Fermer',
    yes: 'Oui',
    no: 'Non',
    name: 'Nom',
    amount: 'Montant',
    date: 'Date',
    status: 'Statut',
    category: 'Catégorie',
    description: 'Description',
    notes: 'Notes',
    total: 'Total',
    payment: 'Paiement',
    cash: 'Espèces',
    mobile_money: 'Mobile Money',
    credit: 'Crédit',
    bank: 'Banque',
    // Business Plan
    bp_title: 'Créateur de Business Plan',
    bp_subtitle: 'Générez un plan professionnel personnalisé en quelques minutes',
    bp_generate: '🚀 Générer mon Business Plan',
    bp_generating: 'Génération de votre business plan…',
    bp_new: 'Créer un nouveau business plan',
    // Settings
    settings_title: 'Paramètres',
    settings_subtitle: 'Configuration de l\'application',
    company_profile: 'Profil commercial',
    notifications: 'Alertes & Notifications',
    exchange_rate: 'Taux de Change CDF/USD',
    whatsapp: 'WhatsApp API',
    language: 'Langue',
    // Language picker
    lang_fr: 'Français',
    lang_en: 'English',
    lang_ln: 'Lingala',
  },
  en: {
    // Nav
    nav_dashboard: 'Dashboard',
    nav_clients: 'Clients',
    nav_invoices: 'Invoices',
    nav_stock: 'Inventory',
    nav_messaging: 'Messaging',
    nav_accounting: 'Accounting',
    nav_sales: 'Sales',
    nav_marketing: 'Marketing',
    nav_finance: 'Personal Finance',
    nav_business_plan: 'Business Plan',
    nav_assistant: 'AI Assistant',
    nav_settings: 'Settings',
    // Dashboard
    daily_objective: 'Daily Sales Target',
    total_revenue: 'Total Revenue',
    net_profit: 'Net Profit',
    expenses: 'Expenses',
    clients: 'Clients',
    products: 'Products',
    sales: 'Sales',
    invoices: 'Invoices',
    pending: 'Pending',
    paid: 'Paid',
    overdue: 'Overdue',
    stock_alerts: 'Stock Alerts',
    low_stock: 'Low stock',
    quick_actions: 'Quick Actions',
    new_sale: 'New Sale',
    new_invoice: 'New Invoice',
    new_client: 'New Client',
    add_stock: 'Add Stock',
    weekly_revenue: 'Weekly Revenue',
    margin: 'Margin',
    // General
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    generate: 'Generate',
    loading: 'Loading…',
    confirm: 'Confirm',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    name: 'Name',
    amount: 'Amount',
    date: 'Date',
    status: 'Status',
    category: 'Category',
    description: 'Description',
    notes: 'Notes',
    total: 'Total',
    payment: 'Payment',
    cash: 'Cash',
    mobile_money: 'Mobile Money',
    credit: 'Credit',
    bank: 'Bank',
    // Business Plan
    bp_title: 'Business Plan Creator',
    bp_subtitle: 'Generate a personalized professional plan in minutes',
    bp_generate: '🚀 Generate my Business Plan',
    bp_generating: 'Generating your business plan…',
    bp_new: 'Create a new business plan',
    // Settings
    settings_title: 'Settings',
    settings_subtitle: 'Application configuration',
    company_profile: 'Business Profile',
    notifications: 'Alerts & Notifications',
    exchange_rate: 'CDF/USD Exchange Rate',
    whatsapp: 'WhatsApp API',
    language: 'Language',
    // Language picker
    lang_fr: 'Français',
    lang_en: 'English',
    lang_ln: 'Lingala',
  },
  ln: {
    // Nav
    nav_dashboard: 'Tableau ya Mosala',
    nav_clients: 'Bakliyé',
    nav_invoices: 'Mabweli',
    nav_stock: 'Biloko',
    nav_messaging: 'Mitinda',
    nav_accounting: 'Bokabeli',
    nav_sales: 'Bateki',
    nav_marketing: 'Bokɔtisi',
    nav_finance: 'Mbongo ya Moto',
    nav_business_plan: 'Mosala Plan',
    nav_assistant: 'Lisalisi ya AI',
    nav_settings: 'Bisaleli',
    // Dashboard
    daily_objective: 'Elongi ya Mokolo',
    total_revenue: 'Mbongo Nionso',
    net_profit: 'Litomba',
    expenses: 'Mabimisi',
    clients: 'Bakliyé',
    products: 'Biloko',
    sales: 'Bateki',
    invoices: 'Mabweli',
    pending: 'Kozela',
    paid: 'Lilembi',
    overdue: 'Eleki ntango',
    stock_alerts: 'Makebisi ya Biloko',
    low_stock: 'Biloko mike',
    quick_actions: 'Misala ya Lomba',
    new_sale: 'Teka sika',
    new_invoice: 'Bweli sika',
    new_client: 'Kliyé sika',
    add_stock: 'Yaka biloko',
    weekly_revenue: 'Mbongo ya Pɔsɔ',
    margin: 'Ndelo',
    // General
    save: 'Bomba',
    cancel: 'Silika',
    delete: 'Boma',
    edit: 'Bongola',
    add: 'Yaka',
    search: 'Luka',
    filter: 'Panza',
    export: 'Tinda Libanda',
    generate: 'Sala',
    loading: 'Kozela…',
    confirm: 'Nzela',
    close: 'Zika',
    yes: 'Iyo',
    no: 'Te',
    name: 'Nkombo',
    amount: 'Mbongo',
    date: 'Mokolo',
    status: 'Etat',
    category: 'Ndenge',
    description: 'Koloba',
    notes: 'Makomi',
    total: 'Nyonso',
    payment: 'Lilembi',
    cash: 'Mbongo ya Loboko',
    mobile_money: 'Mobile Money',
    credit: 'Kredí',
    bank: 'Banki',
    // Business Plan
    bp_title: 'Mosala Plan ya Bizinesi',
    bp_subtitle: 'Sala plan ya mosala na minutes mike',
    bp_generate: '🚀 Sala Plan na Ngai',
    bp_generating: 'Tozali kosala plan na yo…',
    bp_new: 'Sala plan sika ya bizinesi',
    // Settings
    settings_title: 'Bisaleli',
    settings_subtitle: 'Kobongisa app',
    company_profile: 'Koloba ya Moziki',
    notifications: 'Makebisi',
    exchange_rate: 'Ntalo ya CDF/USD',
    whatsapp: 'WhatsApp API',
    language: 'Lokota',
    // Language picker
    lang_fr: 'Français',
    lang_en: 'English',
    lang_ln: 'Lingala',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('nzimbu_lang') || 'fr');

  const switchLang = (l) => {
    localStorage.setItem('nzimbu_lang', l);
    setLang(l);
  };

  const t = (key) => translations[lang]?.[key] ?? translations['fr']?.[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}