import { createContext, useContext, useState } from 'react';

export const translations = {
  fr: {
    // Nav
    nav_dashboard: 'Tableau de Bord',
    nav_clients: 'Clients',
    nav_invoices: 'Factures',
    nav_stock: 'Stock',
    nav_messaging: 'Messagerie',
    nav_accounting: 'Comptabilité',
    nav_sales: 'Ventes',
    nav_marketing: 'Marketing',
    nav_finance: 'Finance Perso',
    nav_business_plan: 'Business Plan',
    nav_assistant: 'Assistant IA',
    nav_settings: 'Paramètres',
    // Dashboard
    daily_objective: 'Objectif Ventes Quotidien',
    total_revenue: 'Chiffre d\'Affaires',
    net_profit: 'Bénéfice Net',
    expenses: 'Dépenses',
    clients: 'Clients',
    products: 'Produits',
    sales: 'Ventes',
    invoices: 'Factures',
    pending: 'En attente',
    paid: 'Payé',
    overdue: 'En retard',
    stock_alerts: 'Alertes Stock',
    low_stock: 'Stock bas',
    quick_actions: 'Actions Rapides',
    new_sale: 'Nouvelle Vente',
    new_invoice: 'Nouvelle Facture',
    new_client: 'Nouveau Client',
    add_stock: 'Ajouter Stock',
    weekly_revenue: 'Revenus Hebdomadaires',
    margin: 'Marge',
    // General
    save: 'Sauvegarder',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    search: 'Rechercher',
    filter: 'Filtrer',
    export: 'Exporter',
    generate: 'Générer',
    loading: 'Chargement…',
    confirm: 'Confirmer',
    close: 'Fermer',
    yes: 'Oui',
    no: 'Non',
    name: 'Nom',
    amount: 'Montant',
    date: 'Date',
    status: 'Statut',
    category: 'Catégorie',
    description: 'Description',
    notes: 'Notes',
    total: 'Total',
    payment: 'Paiement',
    cash: 'Espèces',
    mobile_money: 'Mobile Money',
    credit: 'Crédit',
    bank: 'Banque',
    // Business Plan
    bp_title: 'Créateur de Business Plan',
    bp_subtitle: 'Générez un plan professionnel personnalisé en quelques minutes',
    bp_generate: '🚀 Générer mon Business Plan',
    bp_generating: 'Génération de votre business plan…',
    bp_new: 'Créer un nouveau business plan',
    // Settings
    settings_title: 'Paramètres',
    settings_subtitle: 'Configuration de l\'application',
    company_profile: 'Profil commercial',
    notifications: 'Alertes & Notifications',
    exchange_rate: 'Taux de Change CDF/USD',
    whatsapp: 'WhatsApp API',
    language: 'Langue',
    // Clients
    client_name: 'Nom du client',
    phone: 'Téléphone',
    location: 'Localisation',
    segment: 'Segment',
    trust_score: 'Score de confiance',
    credit_limit: 'Limite de crédit',
    credit_due: 'Crédit dû',
    total_revenue_client: 'CA total client',
    add_client: 'Ajouter un client',
    edit_client: 'Modifier le client',
    // Invoices
    invoice_number: 'N° Facture',
    issue_date: 'Date d\'émission',
    due_date: 'Date d\'échéance',
    subtotal: 'Sous-total',
    new_invoice: 'Nouvelle Facture',
    send_whatsapp: 'Envoyer par WhatsApp',
    mark_paid: 'Marquer payé',
    // Stock
    product_name: 'Nom du produit',
    sku: 'SKU',
    unit: 'Unité',
    selling_price: 'Prix de vente',
    cost_price: 'Prix de revient',
    stock_qty: 'Quantité en stock',
    reorder_point: 'Seuil de réappro.',
    add_product: 'Ajouter un produit',
    out_of_stock: 'Rupture de stock',
    // Sales
    quantity: 'Quantité',
    unit_price: 'Prix unitaire',
    profit: 'Bénéfice',
    payment_method: 'Mode de paiement',
    pos: 'Point de Vente',
    history: 'Historique',
    cart: 'Panier',
    complete_sale: 'Finaliser la Vente',
    anonymous_client: 'Client anonyme',
    // Marketing
    new_post: 'Nouveau Post',
    platform: 'Plateforme',
    schedule: 'Planifier',
    published: 'Publié',
    draft: 'Brouillon',
    scheduled: 'Planifié',
    generate_with_ai: 'Générer avec IA',
    // Finance Perso
    income: 'Revenus',
    budget: 'Budget',
    savings: 'Épargne',
    debt: 'Dette',
    savings_goal: 'Objectif d\'épargne',
    monthly_payment: 'Paiement mensuel',
    interest_rate: 'Taux d\'intérêt',
    remaining: 'Restant',
    // Accounting
    journal: 'Journal',
    report: 'Rapport',
    tax: 'Taxes',
    net_margin: 'Marge nette',
    gross_revenue: 'CA brut',
    add_expense: 'Ajouter une dépense',
    // Messaging
    reply: 'Répondre',
    send: 'Envoyer',
    conversation: 'Conversation',
    no_messages: 'Aucun message',
    // Notifications
    notifications: 'Notifications',
    mark_all_read: 'Tout marquer lu',
    no_notifications: 'Aucune notification',
    // Settings
    save_changes: 'Sauvegarder les modifications',
    business_name: 'Nom de l\'entreprise',
    currency: 'Devise',
    timezone: 'Fuseau horaire',
    // Language picker
    lang_fr: 'Français',
    lang_en: 'English',
    lang_ln: 'Lingala',
  },
  en: {
    // Nav
    nav_dashboard: 'Dashboard',
    nav_clients: 'Clients',
    nav_invoices: 'Invoices',
    nav_stock: 'Inventory',
    nav_messaging: 'Messaging',
    nav_accounting: 'Accounting',
    nav_sales: 'Sales',
    nav_marketing: 'Marketing',
    nav_finance: 'Personal Finance',
    nav_business_plan: 'Business Plan',
    nav_assistant: 'AI Assistant',
    nav_settings: 'Settings',
    // Dashboard
    daily_objective: 'Daily Sales Target',
    total_revenue: 'Total Revenue',
    net_profit: 'Net Profit',
    expenses: 'Expenses',
    clients: 'Clients',
    products: 'Products',
    sales: 'Sales',
    invoices: 'Invoices',
    pending: 'Pending',
    paid: 'Paid',
    overdue: 'Overdue',
    stock_alerts: 'Stock Alerts',
    low_stock: 'Low stock',
    quick_actions: 'Quick Actions',
    new_sale: 'New Sale',
    new_invoice: 'New Invoice',
    new_client: 'New Client',
    add_stock: 'Add Stock',
    weekly_revenue: 'Weekly Revenue',
    margin: 'Margin',
    // General
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    generate: 'Generate',
    loading: 'Loading…',
    confirm: 'Confirm',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    name: 'Name',
    amount: 'Amount',
    date: 'Date',
    status: 'Status',
    category: 'Category',
    description: 'Description',
    notes: 'Notes',
    total: 'Total',
    payment: 'Payment',
    cash: 'Cash',
    mobile_money: 'Mobile Money',
    credit: 'Credit',
    bank: 'Bank',
    // Business Plan
    bp_title: 'Business Plan Creator',
    bp_subtitle: 'Generate a personalized professional plan in minutes',
    bp_generate: '🚀 Generate my Business Plan',
    bp_generating: 'Generating your business plan…',
    bp_new: 'Create a new business plan',
    // Settings
    settings_title: 'Settings',
    settings_subtitle: 'Application configuration',
    company_profile: 'Business Profile',
    notifications: 'Alerts & Notifications',
    exchange_rate: 'CDF/USD Exchange Rate',
    whatsapp: 'WhatsApp API',
    language: 'Language',
    // Clients
    client_name: 'Client Name',
    phone: 'Phone',
    location: 'Location',
    segment: 'Segment',
    trust_score: 'Trust Score',
    credit_limit: 'Credit Limit',
    credit_due: 'Credit Due',
    total_revenue_client: 'Total Client Revenue',
    add_client: 'Add Client',
    edit_client: 'Edit Client',
    // Invoices
    invoice_number: 'Invoice #',
    issue_date: 'Issue Date',
    due_date: 'Due Date',
    subtotal: 'Subtotal',
    new_invoice: 'New Invoice',
    send_whatsapp: 'Send via WhatsApp',
    mark_paid: 'Mark as Paid',
    // Stock
    product_name: 'Product Name',
    sku: 'SKU',
    unit: 'Unit',
    selling_price: 'Selling Price',
    cost_price: 'Cost Price',
    stock_qty: 'Stock Qty',
    reorder_point: 'Reorder Point',
    add_product: 'Add Product',
    out_of_stock: 'Out of Stock',
    // Sales
    quantity: 'Quantity',
    unit_price: 'Unit Price',
    profit: 'Profit',
    payment_method: 'Payment Method',
    pos: 'Point of Sale',
    history: 'History',
    cart: 'Cart',
    complete_sale: 'Complete Sale',
    anonymous_client: 'Anonymous Client',
    // Marketing
    new_post: 'New Post',
    platform: 'Platform',
    schedule: 'Schedule',
    published: 'Published',
    draft: 'Draft',
    scheduled: 'Scheduled',
    generate_with_ai: 'Generate with AI',
    // Finance Perso
    income: 'Income',
    budget: 'Budget',
    savings: 'Savings',
    debt: 'Debt',
    savings_goal: 'Savings Goal',
    monthly_payment: 'Monthly Payment',
    interest_rate: 'Interest Rate',
    remaining: 'Remaining',
    // Accounting
    journal: 'Journal',
    report: 'Report',
    tax: 'Taxes',
    net_margin: 'Net Margin',
    gross_revenue: 'Gross Revenue',
    add_expense: 'Add Expense',
    // Messaging
    reply: 'Reply',
    send: 'Send',
    conversation: 'Conversation',
    no_messages: 'No messages',
    // Notifications
    notifications: 'Notifications',
    mark_all_read: 'Mark all as read',
    no_notifications: 'No notifications',
    // Settings
    save_changes: 'Save Changes',
    business_name: 'Business Name',
    currency: 'Currency',
    timezone: 'Timezone',
    // Language picker
    lang_fr: 'Français',
    lang_en: 'English',
    lang_ln: 'Lingala',
  },
  ln: {
    // Nav
    nav_dashboard: 'Tableau ya Mosala',
    nav_clients: 'Bakliyé',
    nav_invoices: 'Mabweli',
    nav_stock: 'Biloko',
    nav_messaging: 'Mitinda',
    nav_accounting: 'Bokabeli',
    nav_sales: 'Bateki',
    nav_marketing: 'Bokɔtisi',
    nav_finance: 'Mbongo ya Moto',
    nav_business_plan: 'Mosala Plan',
    nav_assistant: 'Lisalisi ya AI',
    nav_settings: 'Bisaleli',
    // Dashboard
    daily_objective: 'Elongi ya Mokolo',
    total_revenue: 'Mbongo Nionso',
    net_profit: 'Litomba',
    expenses: 'Mabimisi',
    clients: 'Bakliyé',
    products: 'Biloko',
    sales: 'Bateki',
    invoices: 'Mabweli',
    pending: 'Kozela',
    paid: 'Lilembi',
    overdue: 'Eleki ntango',
    stock_alerts: 'Makebisi ya Biloko',
    low_stock: 'Biloko mike',
    quick_actions: 'Misala ya Lomba',
    new_sale: 'Teka sika',
    new_invoice: 'Bweli sika',
    new_client: 'Kliyé sika',
    add_stock: 'Yaka biloko',
    weekly_revenue: 'Mbongo ya Pɔsɔ',
    margin: 'Ndelo',
    // General
    save: 'Bomba',
    cancel: 'Silika',
    delete: 'Boma',
    edit: 'Bongola',
    add: 'Yaka',
    search: 'Luka',
    filter: 'Panza',
    export: 'Tinda Libanda',
    generate: 'Sala',
    loading: 'Kozela…',
    confirm: 'Nzela',
    close: 'Zika',
    yes: 'Iyo',
    no: 'Te',
    name: 'Nkombo',
    amount: 'Mbongo',
    date: 'Mokolo',
    status: 'Etat',
    category: 'Ndenge',
    description: 'Koloba',
    notes: 'Makomi',
    total: 'Nyonso',
    payment: 'Lilembi',
    cash: 'Mbongo ya Loboko',
    mobile_money: 'Mobile Money',
    credit: 'Kredí',
    bank: 'Banki',
    // Business Plan
    bp_title: 'Mosala Plan ya Bizinesi',
    bp_subtitle: 'Sala plan ya mosala na minutes mike',
    bp_generate: '🚀 Sala Plan na Ngai',
    bp_generating: 'Tozali kosala plan na yo…',
    bp_new: 'Sala plan sika ya bizinesi',
    // Settings
    settings_title: 'Bisaleli',
    settings_subtitle: 'Kobongisa app',
    company_profile: 'Koloba ya Moziki',
    notifications: 'Makebisi',
    exchange_rate: 'Ntalo ya CDF/USD',
    whatsapp: 'WhatsApp API',
    language: 'Lokota',
    // Clients
    client_name: 'Nkombo ya Kliyé',
    phone: 'Nimero ya Foni',
    location: 'Esika',
    segment: 'Ndenge',
    trust_score: 'Motema ya Kondima',
    credit_limit: 'Ndelo ya Kredí',
    credit_due: 'Kredí ya Kozala',
    total_revenue_client: 'Mbongo Nionso ya Kliyé',
    add_client: 'Yaka Kliyé',
    edit_client: 'Bongola Kliyé',
    // Invoices
    invoice_number: 'N° Bweli',
    issue_date: 'Mokolo ya Kosala',
    due_date: 'Mokolo ya Kozala',
    subtotal: 'Nyonso mike',
    new_invoice: 'Bweli Sika',
    send_whatsapp: 'Tinda na WhatsApp',
    mark_paid: 'Lilembi esalemi',
    // Stock
    product_name: 'Nkombo ya Biloko',
    sku: 'SKU',
    unit: 'Ndimbola',
    selling_price: 'Ntalo ya Koteka',
    cost_price: 'Ntalo ya Kobonga',
    stock_qty: 'Boumbu ya Biloko',
    reorder_point: 'Ndelo ya Kozongisa',
    add_product: 'Yaka Biloko',
    out_of_stock: 'Biloko Esilaki',
    // Sales
    quantity: 'Boumbu',
    unit_price: 'Ntalo ya Moko',
    profit: 'Litomba',
    payment_method: 'Ndenge ya Lilembi',
    pos: 'Esika ya Koteka',
    history: 'Mbunga',
    cart: 'Saki',
    complete_sale: 'Tia Etekeli',
    anonymous_client: 'Kliyé ya Kozeba Te',
    // Marketing
    new_post: 'Makomi Sika',
    platform: 'Esika ya Koloba',
    schedule: 'Bongisa Ntango',
    published: 'Ebimaki',
    draft: 'Ekomami kaka',
    scheduled: 'Ebongisami',
    generate_with_ai: 'Sala na AI',
    // Finance Perso
    income: 'Mbongo Ekoyaka',
    budget: 'Bujé',
    savings: 'Epeli',
    debt: 'Ndeke',
    savings_goal: 'Elongi ya Epeli',
    monthly_payment: 'Lilembi ya Sanza',
    interest_rate: 'Ntalo ya Ntaka',
    remaining: 'Ekozali',
    // Accounting
    journal: 'Buku ya Mosala',
    report: 'Rapport',
    tax: 'Mpako',
    net_margin: 'Ndelo ya Litomba',
    gross_revenue: 'Mbongo Nionso',
    add_expense: 'Yaka Mabimisi',
    // Messaging
    reply: 'Yamba',
    send: 'Tinda',
    conversation: 'Lilobeli',
    no_messages: 'Mitinda ezali te',
    // Notifications
    notifications: 'Makebisi',
    mark_all_read: 'Tanga Nionso',
    no_notifications: 'Makebisi ezali te',
    // Settings
    save_changes: 'Bomba Bongoli',
    business_name: 'Nkombo ya Moziki',
    currency: 'Mbongo ya Ekolo',
    timezone: 'Ntango ya Esika',
    // Language picker
    lang_fr: 'Français',
    lang_en: 'English',
    lang_ln: 'Lingala',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('nzimbu_lang') || 'fr');

  const switchLang = (l) => {
    localStorage.setItem('nzimbu_lang', l);
    setLang(l);
  };

  const t = (key) => translations[lang]?.[key] ?? translations['fr']?.[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}